const diseaseClass = [
    'Actinic Cheilitis',
    'Actinic Keratosis',
    'Acute Urticaria',
    'Allergic Contact Dermatitis',
    'Alopecia Areata',
    'Atopic Dermatitis',
    'Basal Cell Carcinoma',
    'Bowens Disease',
    'Candidiasis',
    'Chondrodermatitis',
    'Ctcl',
    'Dermatofibroma',
    'Distal Subungual Onychomycosis',
    'Eczema',
    'Eczema Herpeticum',
    'Epidermal Cyst',
    'Erythema',
    'Herpes',
    'Intertrigo',
    'Keloids',
    'Keratoacanthoma',
    'Lentigo',
    'Lichen Planus',
    'Lupus',
    'Morphea',
    'Nevus',
    'Onycholysis',
    'Porokeratosis',
    'Porphyrias',
    'Psoriasis',
    'Rhus Dermatitis',
    'Scabies',
    'Schamberg',
    'Scleroderma',
    'Sebaceous',
    'Seborrheic Keratoses',
    'Skin Tags Polyps',
    'Squamous',
    'Statis Dermatitis',
    'Sun Damaged Skin',
    'Tinea',
    'Varicella',
    'Vasculitis',
    'Vitiligo',
    'Warts'
]

module.exports = diseaseClass